import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { NextAuthProvider } from '~/components/layout/NextAuthProvider';
import { SWRProvider } from '~/components/layout/SWRProvider';
import { Gabarito } from 'next/font/google';

const gabarito = Gabarito({
  subsets: ['latin'],
  variable: '--font-gabarito',
  display: 'swap',
  weight: ['400', '500']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={gabarito.variable}>
      <body className="antialiased font-mono">
        <div className="max-w-5xl w-full mx-auto px-4">
          <ThemeProvider attribute="class" defaultTheme="light">
            <SWRProvider>
              <NextAuthProvider>{children}</NextAuthProvider>
            </SWRProvider>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
